spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgres-user:5432/user_service
    username: postgres
    password: 6531503042
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/